# Generated by Django 4.0.3 on 2022-03-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_archive_olddebts_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olddebts',
            options={'ordering': ('-from_date',)},
        ),
    ]
