# Generated by Django 4.0.3 on 2022-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_olddebts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
