# Generated by Django 4.0.3 on 2022-03-04 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_client_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=30,),
            preserve_default=False,
        ),
    ]
