# Generated by Django 4.0.3 on 2022-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='old_debts',
            field=models.IntegerField(default=0),
        ),
    ]
