# Generated by Django 4.0.3 on 2022-03-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_client_old_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
