# Generated by Django 4.0.3 on 2022-03-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='payed',
            new_name='paid',
        ),
    ]
