# Generated by Django 4.0.3 on 2022-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_payed_client_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
