# Generated by Django 4.0.3 on 2022-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_master_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='reported',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='reported',
            field=models.BooleanField(default=True),
        ),
    ]
